# Configuration yamllint (stage validate + pre-commit).
---
extends: default

rules:
  line-length:
    max: 160
  document-start:
    present: true
  comments:
    min-spaces-from-content: 1
  truthy:
    allowed-values: ["true", "false", "yes", "no"]
  braces:
    max-spaces-inside: 1

ignore: |
  .terraform/
  kolla/globals.yml.j2
  .gitlab-ci.yml
  .gitlab/
  artifacts/
